Pick CI settings from main branch

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -3,34 +3,100 @@ name: test
 on: [workflow_dispatch, push, pull_request]
 
 env:
-  FOUNDRY_PROFILE: ci
+  ANVIL_PRIVATE_KEY: ${{secrets.ANVIL_PRIVATE_KEY}}
+  ANVIL_URL: ${{secrets.ANVIL_RPC_URL}}
+
 
 jobs:
-  check:
+  integration-tests-e2e-grumpkin:
+    needs: [ unit-tests ]
     strategy:
       fail-fast: true
 
-    name: Foundry project
-    runs-on: ubuntu-latest
+    name: E2E verification (Grumpkin)
+    runs-on: [ self-hosted ]
     steps:
       - uses: actions/checkout@v3
         with:
           submodules: recursive
-
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.8
 
       - name: Install Foundry
         uses: foundry-rs/foundry-toolchain@v1
         with:
           version: nightly
 
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.8
+
+      - name: Deploy main contract
+        run: |
+          echo "CONTRACT_ADDRESS=$(forge script script/Deployment.s.sol:NovaGrumpkinVerifierDeployer --fork-url $ANVIL_URL --private-key $ANVIL_PRIVATE_KEY --broadcast --non-interactive | sed -n 's/.*Contract Address: //p' | tail -1)" >> $GITHUB_OUTPUT
+        id: deployment-grumpkin
+
+      - name: Load proof and public parameters
+        run: |
+          python loaderGrumpkin.py verifier-key-grumpkin.json compressed-snark-grumpkin.json ${{steps.deployment-grumpkin.outputs.CONTRACT_ADDRESS}} $ANVIL_URL $ANVIL_PRIVATE_KEY
+
+      - name: Check proof verification status
+        run: |
+          [[ $(cast call ${{steps.deployment-grumpkin.outputs.CONTRACT_ADDRESS}} "verify(uint32,uint256[],uint256[],bool)(bool)" "3" "[1]" "[0]" "true" --private-key $ANVIL_PRIVATE_KEY --rpc-url $ANVIL_URL) == true ]] && exit 0 || exit 1
+
+  #integration-tests-e2e-pasta:
+  #  needs: [unit-tests]
+  #  strategy:
+  #    fail-fast: true
+
+  #  name: E2E verification (Pasta)
+  #  runs-on: [self-hosted]
+  #  steps:
+  #    - uses: actions/checkout@v3
+  #      with:
+  #        submodules: recursive
+
+  #   - name: Install Foundry
+  #      uses: foundry-rs/foundry-toolchain@v1
+  #      with:
+  #        version: nightly
+
+  #    - name: Set up Python
+  #      uses: actions/setup-python@v4
+  #      with:
+  #        python-version: 3.8
+
+  #    - name: Deploy main contract
+  #      run: |
+  #        echo "CONTRACT_ADDRESS=$(forge script script/Deployment.s.sol:NovaPastaVerifierDeployer --fork-url $ANVIL_URL --private-key $ANVIL_PRIVATE_KEY --broadcast --non-interactive | sed -n 's/.*Contract Address: //p' | tail -1)" >> $GITHUB_OUTPUT
+  #      id: deployment-pasta
+
+  #    - name: Load proof and public parameters
+  #      run: |
+  #        python loaderPasta.py verifier-key-pasta.json compressed-snark-pasta.json ${{steps.deployment-pasta.outputs.CONTRACT_ADDRESS}} $ANVIL_URL $ANVIL_PRIVATE_KEY
+
+  #    - name: Check proof verification status
+  #      run: |
+  #        [[ $(cast call ${{steps.deployment-pasta.outputs.CONTRACT_ADDRESS}} "verify(uint32,uint256[],uint256[],bool)(bool)" "3" "[1]" "[0]" "true" --private-key $ANVIL_PRIVATE_KEY --rpc-url $ANVIL_URL) == true ]] && exit 0 || exit 1
+
+  unit-tests:
+    strategy:
+      fail-fast: true
+
+    name: Unit Tests
+    runs-on: [self-hosted]
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          submodules: recursive
+
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.8
+
       - name: Check formatting
         run: |
           forge fmt --check
-        id: formatting
 
       - name: Regenerate Contracts
         run: |
@@ -52,15 +118,12 @@ jobs:
         run: |
           forge --version
           forge build
-        id: build
 
       - name: Run Forge tests
         run: |
           forge test -vvv
-        id: test
 
       - name: Get sizes of compiled contracts
         run: |
           forge --version
           forge build --sizes || true
-        id: build-with-sizes
